In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.style.use('ggplot')

In [2]:
houston_hourly = pd.read_csv('./clean_data/clean_houston_hourly.csv')
cincy_hourly = pd.read_csv('./clean_data/clean_cincy_hourly.csv')
newyork_hourly = pd.read_csv('./clean_data/clean_newyork_hourly.csv')
atlanta_hourly = pd.read_csv('./clean_data/clean_atlanta_hourly.csv')

In [3]:
houston_hourly.head(2)

Unnamed: 0                 DATE  HourlyAltimeterSetting  \
0           0  1948-07-01 00:00:00                     NaN   
1           1  1948-07-01 01:00:00                     NaN   

   HourlyDewPointTemperature  HourlyDryBulbTemperature  HourlyPrecipitation  \
0                 293.705556                294.261111                  0.0   
1                 293.705556                294.261111                  0.0   

   HourlyPressureChange  HourlyPressureTendency  HourlyRelativeHumidity  \
0                   NaN                     NaN                    97.0   
1                   NaN                     NaN                    97.0   

   HourlySeaLevelPressure  ...  HourlyWetBulbTemperature  HourlyWindDirection  \
0                   30.05  ...                293.705556                315.0   
1                   30.05  ...                293.705556                338.0   

   HourlyWindGustSpeed  HourlyWindSpeed  YEAR  MONTH  DAY  HOUR        CITY  \
0                  NaN              3.0  1948      7    1     0  Houston_TX   
1                  NaN              6.0  1948      7    1     1  Houston_TX   

   DECADE  
0    1940  
1    1940  

[2 rows x 22 columns]

#### Drop_columns
A lot of features only start getting measured in the 1990s (say), which gives the model an unfair advantage. So let's drop them:

In [4]:
drop_columns = ['Unnamed: 0', 'HourlyPrecipitation','HourlyPressureChange','HourlyPressureTendency','HourlyWindGustSpeed', 
                'DATE','YEAR','CITY','DECADE']

# for the aggregated DF, which doesn't include "CITY" (since we use pd.get_dummies())
drop_columns2 = ['Unnamed: 0', 'HourlyPrecipitation','HourlyPressureChange','HourlyPressureTendency','HourlyWindGustSpeed', 
                'DATE','YEAR','DECADE']

#### Houston LogReg

In [5]:
# set up X and Y
Xh = houston_hourly.drop(columns=drop_columns).fillna(0)
yh = houston_hourly['DECADE']

Xh_train, Xh_test, yh_train, yh_test = train_test_split(Xh,yh)

sc = StandardScaler()
Xh_train_sc = sc.fit_transform(Xh_train)
Xh_test_sc = sc.transform(Xh_test)

In [6]:
# instantiate regressor
logreg = LogisticRegression()

logreg.fit(Xh_train_sc, yh_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
print(f'Houston LogisticRegression train score: {logreg.score(Xh_train_sc, yh_train)}')
print(f'Houston LogisticRegression test score: {logreg.score(Xh_test_sc, yh_test)}')

Houston LogisticRegression train score: 0.23019382994868018
Houston LogisticRegression test score: 0.23169294387834133


#### Cincinnati LogReg

In [12]:
# set up X and Y
Xc = cincy_hourly.drop(columns=drop_columns).fillna(0)
yc = cincy_hourly['DECADE']

Xc_train, Xc_test, yc_train, yc_test = train_test_split(Xc,yc)

sc = StandardScaler()
Xc_train_sc = sc.fit_transform(Xc_train)
Xc_test_sc = sc.transform(Xc_test)

In [13]:
# instantiate regressor
logreg = LogisticRegression()

logreg.fit(Xc_train_sc, yc_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
print(f"Cincinnati LogisticRegression train score: {logreg.score(Xc_train_sc, yc_train)}")
print(f"Cincinnati LogisticRegression test score: {logreg.score(Xc_test_sc, yc_test)}")

Cincinnati LogisticRegression train score: 0.31253412126541447
Cincinnati LogisticRegression test score: 0.3122980077389994


#### New York LogReg

In [17]:
# set up X and Y
Xn = newyork_hourly.drop(columns=drop_columns).fillna(0)
yn = newyork_hourly['DECADE']

Xn_train, Xn_test, yn_train, yn_test = train_test_split(Xn,yn)

sc = StandardScaler()
Xn_train_sc = sc.fit_transform(Xn_train)
Xn_test_sc = sc.transform(Xn_test)

In [18]:
# instantiate regressor
logreg = LogisticRegression()

logreg.fit(Xn_train_sc, yn_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [24]:
print(f"New York LogisticRegression train score: {logreg.score(Xn_train_sc, yn_train)}")
print(f"New York LogisticRegression test score: {logreg.score(Xn_test_sc, yn_test)}")

New York LogisticRegression train score: 0.3257050373762263
New York LogisticRegression test score: 0.3255152984586234


#### Atlanta LogReg

In [20]:
# set up X and Y
Xa = atlanta_hourly.drop(columns=drop_columns).fillna(0)
ya = atlanta_hourly['DECADE']

Xa_train, Xa_test, ya_train, ya_test = train_test_split(Xa,ya)

sc = StandardScaler()
Xa_train_sc = sc.fit_transform(Xa_train)
Xa_test_sc = sc.transform(Xa_test)

In [21]:
# instantiate regressor
logreg = LogisticRegression()

logreg.fit(Xa_train_sc, ya_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
print(f"Atlanta LogisticRegression train score: {logreg.score(Xa_train_sc, ya_train)}")
print(f"Atlanta LogisticRegression test score: {logreg.score(Xa_test_sc, ya_test)}")

Atlanta LogisticRegression train score: 0.40424411118192577
Atlanta LogisticRegression test score: 0.404722729844505


In [27]:
all_hourly = pd.concat([houston_hourly,cincy_hourly,newyork_hourly,atlanta_hourly])
all_hourly.head()

Unnamed: 0                 DATE  HourlyAltimeterSetting  \
0           0  1948-07-01 00:00:00                     NaN   
1           1  1948-07-01 01:00:00                     NaN   
2           2  1948-07-01 02:00:00                     NaN   
3           3  1948-07-01 03:00:00                     NaN   
4           4  1948-07-01 04:00:00                     NaN   

   HourlyDewPointTemperature  HourlyDryBulbTemperature  HourlyPrecipitation  \
0                 293.705556                294.261111                  0.0   
1                 293.705556                294.261111                  0.0   
2                 293.705556                294.261111                  0.0   
3                 293.705556                294.261111                  0.0   
4                 293.150000                293.705556                  0.0   

   HourlyPressureChange  HourlyPressureTendency  HourlyRelativeHumidity  \
0                   NaN                     NaN                    97.0   
1                   NaN                     NaN                    97.0   
2                   NaN                     NaN                    97.0   
3                   NaN                     NaN                    97.0   
4                   NaN                     NaN                    96.0   

   HourlySeaLevelPressure  ...  HourlyWetBulbTemperature  HourlyWindDirection  \
0                   30.05  ...                293.705556                315.0   
1                   30.05  ...                293.705556                338.0   
2                   30.04  ...                293.705556                360.0   
3                   30.04  ...                293.705556                 45.0   
4                   30.04  ...                293.150000                338.0   

   HourlyWindGustSpeed  HourlyWindSpeed  YEAR  MONTH  DAY  HOUR        CITY  \
0                  NaN              3.0  1948      7    1     0  Houston_TX   
1                  NaN              6.0  1948      7    1     1  Houston_TX   
2                  NaN              5.0  1948      7    1     2  Houston_TX   
3                  NaN              3.0  1948      7    1     3  Houston_TX   
4                  NaN              8.0  1948      7    1     4  Houston_TX   

   DECADE  
0    1940  
1    1940  
2    1940  
3    1940  
4    1940  

[5 rows x 22 columns]

In [28]:
all_hourly = pd.get_dummies(all_hourly, columns = ['CITY'], drop_first=True)

#### All cities LogReg

In [29]:
# set up X and Y
Xall = all_hourly.drop(columns=drop_columns2).fillna(0)
yall = all_hourly['DECADE']

Xall_train, Xall_test, yall_train, yall_test = train_test_split(Xall,yall)

sc = StandardScaler()
Xall_train_sc = sc.fit_transform(Xall_train)
Xall_test_sc = sc.transform(Xall_test)

In [30]:
# instantiate regressor
logreg = LogisticRegression(max_iter = 100)

logreg.fit(Xall_train_sc, yall_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
print(f"All cities LogisticRegression train score: {logreg.score(Xall_train_sc, yall_train)}")
print(f"All cities LogisticRegression test score: {logreg.score(Xall_test_sc, yall_test)}")

All cities LogisticRegression train score: 0.42350970492551
All cities LogisticRegression test score: 0.4226982110535977


In [33]:
all_preds = logreg.predict(Xall_test_sc)

In [34]:
from sklearn.metrics import multilabel_confusion_matrix

mcm = multilabel_confusion_matrix(all_preds,yall_test)

decades_list = [1940,1950,1960,1970,1980,1990,2000,2010,2020]
for i in range(len(mcm)):
    print(f"*******{decades_list[i]}*******")
    print(mcm[i])
    print('******************')


*******1940*******
[[600703  21243]
 [    79    632]]
******************
*******1950*******
[[449787   9784]
 [ 85453  77633]]
******************
*******1960*******
[[544034  44934]
 [ 21038  12651]]
******************
*******1970*******
[[549955  58959]
 [  7061   6682]]
******************
*******1980*******
[[500813  61931]
 [ 35115  24798]]
******************
*******1990*******
[[474260  59253]
 [ 57938  31206]]
******************
*******2000*******
[[474299  66629]
 [ 56972  24757]]
******************
*******2010*******
[[405309  36706]
 [ 95805  84837]]
******************
*******2020*******
[[622635     22]
 [     0      0]]
******************


In [35]:
sum1=0
sum2=0
sum3=0
sum4=0

for i in range(len(mcm)):
    sum1 += mcm[i][0][0]
    sum2 += mcm[i][0][1]
    sum3 += mcm[i][1][0]
    sum4 += mcm[i][1][1]

total = sum1 + sum2 + sum3 + sum4
print(f"True positives: {sum1/total}")
print(f"False positives: {sum2/total}")
print(f"False negatives: {sum3/total}")
print(f"True negatives: {sum4/total}")

True positives: 0.824744245672622
False positives: 0.06414464321626692
False negatives: 0.06414464321626692
True negatives: 0.04696646789484419


In [40]:
logreg.coef_

array([[-5.15808922e+00, -2.27733844e-01,  3.56211433e-01,
         4.65378618e-01,  1.51923965e+00,  1.34451665e+00,
         3.38596711e-01, -2.93506637e-01,  4.66546924e-03,
         1.81760101e-01,  2.80964578e-01,  1.77046777e-01,
         6.63762833e-02, -2.08552567e-01,  1.51161256e+00,
        -5.13930544e-01],
       [-5.74807133e+00, -2.05019847e-01,  2.16452141e-01,
         2.65735431e-01,  1.74694933e+00,  2.51122611e+00,
         1.62703963e-01,  8.38538771e-01, -2.32388354e-02,
         2.40904711e-01,  1.69485472e-01,  1.74984293e-01,
         4.20266873e-02,  1.66739136e-01,  1.97449073e+00,
        -1.06844737e-01],
       [-5.77628522e+00,  7.33098093e-02, -2.44634695e-01,
         2.34689890e-02,  1.07794325e+00, -1.09250907e-02,
        -4.17719760e-02,  1.94406569e+00,  1.81230988e-02,
        -6.72875968e-02,  1.60781693e-01,  1.77004960e-01,
         8.37299685e-02, -7.06772119e-02,  1.88208249e+00,
        -2.63363719e-01],
       [ 2.75916150e+00,  1.13860415e

In [43]:
all_hourly['DECADE'].value_counts(normalize=True)

2010    0.194698
2000    0.146619
1990    0.145598
1950    0.140679
1980    0.139516
1970    0.105104
1960    0.092673
1940    0.035067
2020    0.000047
Name: DECADE, dtype: float64